language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  python manage.py migrate
  python manage.py runserver
# before_install:
#   - pip install codecov
#   - pip install coverage
# after_success:
#   - codecov
